spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/BiblioTech_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false




logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator=ERROR
logging.level.org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl=ERROR
logging.level.org.hibernate.engine.jdbc=ERROR
logging.level.org.hibernate=ERROR

# Ocultar contraseña generada de Spring Security
logging.level.org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration=WARN
logging.level.org.springframework.security=WARN
